### ISSUE TITLE
VMCFRE003 bad major version; class=io/github/benas/randombeans/api/EnhancedRandom, offset=6

### ISSUE THREAD

**Issue by pfernandom** [benas/random-beans#174]
I'm trying to execute EnhancedRandom.randomListOf(5, BaseBean.class);

But I'm getting the following exception:

Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=io/github/benas/randombeans/api/EnhancedRandom, offset=6
	at java.lang.ClassLoader.defineClass(ClassLoader.java:324)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:155)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:712)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:93)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1164)
	at java.security.AccessController.doPrivileged(AccessController.java:492)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:595)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:777)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:750)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:326)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:731)

I'm using Maven to include the dependency:

	<dependency>
	    <groupId>io.github.benas</groupId>
	    <artifactId>random-beans</artifactId>
	    <version>3.1.0</version>
	</dependency>

I'm using Java 7. Does random-beans support Java 7?

**Comment by benas** [comment]
Hi,

Random Beans v3.x requires Java 8+. For Java 7, you should use version 2.x.

See details in the [Getting started](https://github.com/benas/random-beans/wiki/Getting-Started) page.

Kind regards
Mahmoud
