### ISSUE TITLE
Abstract enums are not initialized

### ISSUE THREAD

**Issue by mikemaaaa** [benas/random-beans#189]
Hello,

when trying to populate a class that uses an abstract enum, an error is produced. Fixing the issue is possible in the FieldPopulator.generateRandomValue method by adding
```
else if (isEnumType(fieldType))
{
     value = this.beanPopulator.doPopulateBean(fieldType, context);
 }
```
Randomizer:
```
    EnhancedRandom random = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .scanClasspathForConcreteTypes(true)
                .build();

        TestObject testObject = random.nextObject(TestObject.class);
        System.out.println(testObject);
```

Enum:
```
public enum TestEnum
{
    VAL1("Val1")
    {
        @Override
        public String test()
        {
            return "1";
        }
    },
    VAL2("Val2")
    {
        @Override
        public String test()
        {
            return "2";
        }
    };

    private final String displayString;

    TestEnum(String displayString)
    {
        this.displayString = displayString;
    }

    public abstract String test();
}
```
Class:
```
public class TestObject
{
    public TestEnum testEnum;
}
```
Error:
```
io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type class TestObject

	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:122)
	at io.github.benas.randombeans.EnhancedRandomImpl.nextObject(EnhancedRandomImpl.java:72)
	at GenericCloneTestSingle.testTestEnum(GenericCloneTestSingle.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.intellij.junit4.JUnit4TestRunnerUtil$IgnoreIgnoredTestJUnit4ClassRunner.runChild(JUnit4TestRunnerUtil.java:365)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to find a matching concrete subtype of type: class TestEnum
	at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:100)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:79)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:153)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:144)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:118)
	... 24 more
```

**Comment by benas** [comment]
Hi,

Thank you for pointing out this issue. We have a similar problem with enums in #184 

I'll try to resolve both issues with the same fix 😉 

![two birds one stone](https://media.licdn.com/mpr/mpr/p/5/005/098/276/3abd88b.jpg)

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @mikemaaaa 

@PascalSchumacher has kindly fixed this issue. Could you please try it with version 3.3.0-SNAPSHOT and give us your feedback?

Kind regards
Mahmoud
