### ISSUE TITLE
java.time.ZoneId not supported even with the random-beans-jodatime lib

### ISSUE THREAD

**Issue by avillev** [benas/random-beans#260]
While randomizing a bean containing a java.time.ZoneId i get a: 

`Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to create an instance of type: class java.time.ZoneId
	at io.github.benas.randombeans.ObjectFactory.createInstance(ObjectFactory.java:66)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:109)
	... 53 more
Caused by: java.lang.InstantiationError: java.time.ZoneId
	at sun.reflect.GeneratedSerializationConstructorAccessor10.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at io.github.benas.randombeans.ObjectFactory.createNewInstance(ObjectFactory.java:79)
	at io.github.benas.randombeans.ObjectFactory.createInstance(ObjectFactory.java:64)
	... 54 more`

I guess this jsr310 type is not handled.

Regards,
Arnaud

**Comment by benas** [comment]
Hi,

Thank you for reporting this.

JSR310 types are supported since v3.0 : https://github.com/benas/random-beans/wiki/Supported-types#41-java-8-date-time-api-types

But apparently not `ZoneId` :

https://github.com/benas/random-beans/tree/master/random-beans/src/main/java/io/github/benas/randombeans/randomizers/time

I will plan to add a randomizer for it in next release.

Kr
Mahmoud

**Comment by benas** [comment]
Hi @avillev 

Version 3.8.0-SNAPSHOT includes a randomizer for `ZoneId` type.

Can you give it a try?

Kr
Mahmoud

**Comment by avillev** [comment]
Works nice for me !!!

**Comment by benas** [comment]
Great! thank you for taking time to test 👍 

This will go in v3.8.

Keep tuned.
