### ISSUE TITLE
protobuf support ?

### ISSUE THREAD

**Issue by jorgheymans** [benas/random-beans#300]
Protobuf types are peculiar in that you instantiate them via newBuilder() , then call the setters on all attributes, finally call build() to actually instantiate the type. 

```
Person p = Person.newBuilder().setFirstname("foo").setLastname("bar").build();
// what i would like :-)
Person p = random(Person.class);
```

**Comment by benas** [comment]
what prevents you from doing that?

**Comment by jorgheymans** [comment]
Given Person being a protobuf type defined like this for example
```
syntax = "proto3";
option java_outer_classname = "Person";
message Person {
  string firstName = 1;
  string lastName = 2;
}
```
and doing 
```
Person randomPerson = random(Person.class);
```
randomPerson is empty, no values are set for its attributes. I think this is because protobuf really requires you to use the builder of the type to populate the attributes. Using reflection on the type itself does not work. There is an extensive metadata api available on the type though, that would allow you to list the attributes and their types and set them dynamically that way.

**Comment by benas** [comment]
random beans is designed to populate java beans. I don't know how protobuf transforms a type definition like:

```
message Person {
  string firstName = 1;
  string lastName = 2;
}
```

to a `Person.class`. But if `Person.class` ends up being a java bean type (default constructor  + getters/setters), then random beans should be able to randomize the type. Otherwise, this is out of scope of the library. Does this make sense?

**Comment by jorgheymans** [comment]
the generated protobuf classes use the builder pattern, constructors are private 

```java
Person john =
  Person.newBuilder()
    .setId(1234)
    .setName("John Doe")
    .setEmail("jdoe@example.com")
    .addPhones(
      Person.PhoneNumber.newBuilder()
        .setNumber("555-4321")
        .setType(Person.PhoneType.HOME))
    .build();
```


see here https://developers.google.com/protocol-buffers/docs/javatutorial

**Comment by benas** [comment]
Random beans acts at runtime, what I meant is that if `Person.class` ends up having a default constructor + setters *at the bytecode level*, then RB should be able to create a random instance of the type, even if at the API level protobuf forces the user to use the builder pattern. Do you see the point?

Can you please provide the output of `javap Person.class`?

> Using reflection on the type itself does not work.

I'm curious to see the output of `javap`, but I think this is what prevents RB to do its work (because it uses reflection to introspect the target type)

**Comment by jorgheymans** [comment]
here's the output:
```
Compiled from "Person.java"
public final class Person extends com.google.protobuf.GeneratedMessageV3 implements PersonOrBuilder {
  public static final int FIRSTNAME_FIELD_NUMBER;
  public static final int LASTNAME_FIELD_NUMBER;
  public final com.google.protobuf.UnknownFieldSet getUnknownFields();
  public static final com.google.protobuf.Descriptors$Descriptor getDescriptor();
  protected com.google.protobuf.GeneratedMessageV3$FieldAccessorTable internalGetFieldAccessorTable();
  public java.lang.String getFirstName();
  public com.google.protobuf.ByteString getFirstNameBytes();
  public java.lang.String getLastName();
  public com.google.protobuf.ByteString getLastNameBytes();
  public final boolean isInitialized();
  public void writeTo(com.google.protobuf.CodedOutputStream) throws java.io.IOException;
  public int getSerializedSize();
  public boolean equals(java.lang.Object);
  public int hashCode();
  public static Person parseFrom(java.nio.ByteBuffer) throws com.google.protobuf.InvalidProtocolBufferException;
  public static Person parseFrom(java.nio.ByteBuffer, com.google.protobuf.ExtensionRegistryLite) throws com.google.protobuf.InvalidProtocolBufferException;
  public static Person parseFrom(com.google.protobuf.ByteString) throws com.google.protobuf.InvalidProtocolBufferException;
  public static Person parseFrom(com.google.protobuf.ByteString, com.google.protobuf.ExtensionRegistryLite) throws com.google.protobuf.InvalidProtocolBufferException;
  public static Person parseFrom(byte[]) throws com.google.protobuf.InvalidProtocolBufferException;
  public static Person parseFrom(byte[], com.google.protobuf.ExtensionRegistryLite) throws com.google.protobuf.InvalidProtocolBufferException;
  public static Person parseFrom(java.io.InputStream) throws java.io.IOException;
  public static Person parseFrom(java.io.InputStream, com.google.protobuf.ExtensionRegistryLite) throws java.io.IOException;
  public static Person parseDelimitedFrom(java.io.InputStream) throws java.io.IOException;
  public static Person parseDelimitedFrom(java.io.InputStream, com.google.protobuf.ExtensionRegistryLite) throws java.io.IOException;
  public static Person parseFrom(com.google.protobuf.CodedInputStream) throws java.io.IOException;
  public static Person parseFrom(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite) throws java.io.IOException;
  public Person$Builder newBuilderForType();
  public static Person$Builder newBuilder();
  public static Person$Builder newBuilder(Person);
  public Person$Builder toBuilder();
  protected Person$Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3$BuilderParent);
  public static Person getDefaultInstance();
  public static com.google.protobuf.Parser<Person> parser();
  public com.google.protobuf.Parser<Person> getParserForType();
  public Person getDefaultInstanceForType();
  protected com.google.protobuf.Message$Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3$BuilderParent);
  public com.google.protobuf.Message$Builder toBuilder();
  public com.google.protobuf.Message$Builder newBuilderForType();
  public com.google.protobuf.MessageLite$Builder toBuilder();
  public com.google.protobuf.MessageLite$Builder newBuilderForType();
  public com.google.protobuf.MessageLite getDefaultInstanceForType();
  public com.google.protobuf.Message getDefaultInstanceForType();
  static boolean access$200();
  Person(com.google.protobuf.GeneratedMessageV3$Builder, Person$1);
  static java.lang.Object access$402(Person, java.lang.Object);
  static java.lang.Object access$502(Person, java.lang.Object);
  static java.lang.Object access$400(Person);
  static java.lang.Object access$500(Person);
  static com.google.protobuf.UnknownFieldSet access$600(Person);
  static com.google.protobuf.Parser access$700();
  static void access$800(com.google.protobuf.ByteString) throws java.lang.IllegalArgumentException;
  static void access$900(com.google.protobuf.ByteString) throws java.lang.IllegalArgumentException;
  Person(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, Person$1) throws com.google.protobuf.InvalidProtocolBufferException;
  static {};
}

```

**Comment by benas** [comment]
ok thanks I see. Only getters are defined on the `Person` type, the constructor and setters are defined in `Person.Builder`. Have you tried to randomize a `Person.Builder`? Something like:

```java
Person p = random(Person.Builder.class).build();
```

**Comment by benas** [comment]
> Is this because the Person.Builder constructor is private ?

No, RB is able to generate random instances of types having a private constructor. What's happening here is that the `Person.Builder` class has a field `com.google.protobuf.GeneratedMessageV3$BuilderParent` which is an interface and RB cannot instantiate it by default. You should enable the `scanClasspathForConcreteTypes` so that RB tries to find an implementation of that interface in the classpath and create a random instance of it for that field. Can you please try something like:

```java
EnhancedRandom enhancedRandom = new EnhancedRandomBuilder()
                .scanClasspathForConcreteTypes(true)
                .build();
Person person = enhancedRandom.nextObject(Person.Builder.class).build();
```

Hope this works, otherwise, I can't see how RB could handle this complex object graph that protobuf generates and uses to create simple types..

**Comment by jorgheymans** [comment]
Almost ?
```
Exception in thread "main" io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type class randomtest.PersonOuterClass$Person$Builder
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:124)
	at io.github.benas.randombeans.EnhancedRandomImpl.nextObject(EnhancedRandomImpl.java:77)
	at TestRandom.main(TestRandom.java:14)
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to create type: com.google.protobuf.GeneratedMessageV3$BuilderParent for field: builderParent of class: randomtest.PersonOuterClass$Person$Builder
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:85)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:158)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:149)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:120)
	... 2 more
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to find a matching concrete subtype of type: interface com.google.protobuf.GeneratedMessageV3$BuilderParent
	at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:117)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:81)
	... 5 more
```

**Comment by benas** [comment]
> Almost there ?

Unfortunately not.. Because `Unable to find a matching concrete subtype of type: interface com.google.protobuf.GeneratedMessageV3$BuilderParent` means there is no way for RB to generate an instance of this interface.

So adding `protobuf support` is not possible 😞 

Thank you anyway for reporting this and for providing all these details! I'm closing this issue for now.

Best regards,
Mahmoud

**Comment by murdos** [comment]
FYI I've developed and released a small extension library that allows generating protobuf messages with easy-random: https://github.com/murdos/easy-random-protobuf

**Comment by benas** [comment]
@murdos This is awesome! Thank you for doing it and sharing it 👍 May I have your permission to add a reference to it in the readme here: https://github.com/j-easy/easy-random#extensions? Is that ok for you?

**Comment by murdos** [comment]
@benas : Of your course you have my permission! Thanks for proposing it, and thanks for providing ER!

**Comment by benas** [comment]
@murdos Done: 6d058b2ed59de7a141f3182c0bd03df850b1149e. Thank you and happy new year!
